# baseurl: /belen
collections:
  portfolio:
    layout: details.html
    output: true
    permalink: /:collection/:name
defaults:
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: "details"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
exclude:
  - serve.sh
  - _portfolio/example.md
plugins:
  - jekyll-responsive-image
responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 320
    - width: 480
    - width: 800